
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS nik TEXT,
  ADD COLUMN IF NOT EXISTS bidang_usaha TEXT,
  ADD COLUMN IF NOT EXISTS desa TEXT,
  ADD COLUMN IF NOT EXISTS kecamatan TEXT,
  ADD COLUMN IF NOT EXISTS alamat_lengkap TEXT,
  ADD COLUMN IF NOT EXISTS nama_usaha TEXT,
  ADD COLUMN IF NOT EXISTS produk_dihasilkan TEXT,
  ADD COLUMN IF NOT EXISTS tahun_berdiri TEXT,
  ADD COLUMN IF NOT EXISTS perizinan TEXT[],
  ADD COLUMN IF NOT EXISTS bantuan_fasilitasi TEXT,
  ADD COLUMN IF NOT EXISTS kegiatan_dinas_pernah TEXT,
  ADD COLUMN IF NOT EXISTS kegiatan_dinas_sekarang TEXT,
  ADD COLUMN IF NOT EXISTS paguyuban TEXT,
  ADD COLUMN IF NOT EXISTS modal_awal TEXT,
  ADD COLUMN IF NOT EXISTS jumlah_tenaga_kerja TEXT,
  ADD COLUMN IF NOT EXISTS kapasitas_produksi TEXT,
  ADD COLUMN IF NOT EXISTS harga_per_unit TEXT,
  ADD COLUMN IF NOT EXISTS media_pemasaran_online TEXT[],
  ADD COLUMN IF NOT EXISTS daerah_pemasaran_offline TEXT,
  ADD COLUMN IF NOT EXISTS jumlah_penjualan TEXT,
  ADD COLUMN IF NOT EXISTS kesulitan_usaha TEXT,
  ADD COLUMN IF NOT EXISTS pelatihan_diharapkan TEXT,
  ADD COLUMN IF NOT EXISTS akses_permodalan TEXT,
  ADD COLUMN IF NOT EXISTS info_ekspor TEXT;
